sylius_ui:
    events:
        sylius.admin.order.show.payment_content:
            blocks:
                mollie_complete_payment_link:
                    template: '@SyliusMolliePlugin/Admin/Order/Show/Payment/_completePaymentLink.html.twig'
                    priority: 15
                mollie_refund:
                    template: '@SyliusMolliePlugin/Admin/Order/Show/Payment/_refund.html.twig'
                    priority: 5
