sylius_ui:
    events:
        sylius.admin.create:
            blocks:
                payment_method_onboarding:
                    template: '@SyliusMolliePlugin/Ui/OnboardingWizard/_navigation.html.twig'
                    priority: 15
        sylius.admin.update:
            blocks:
                payment_method_onboarding:
                    template: '@SyliusMolliePlugin/Ui/OnboardingWizard/_navigation.html.twig'
                    priority: 15
