sylius_ui:
    events:
        sylius.shop.cart.items:
            blocks:
                cart_items_details:
                    template: "@SyliusMolliePlugin/Shop/Cart/_productVariantsDetails.html.twig"
                    priority: -10
        sylius.shop.checkout.complete.summary:
            blocks:
                cart_items_details:
                    template: "@SyliusMolliePlugin/Shop/Summary/_productVariantsDetails.html.twig"
                    priority: -10
