framework:
    workflows:
        !php/const Sylius\Component\Shipping\ShipmentTransitions::GRAPH:
            transitions:
                !php/const Sylius\MolliePlugin\StateMachine\ShipmentTransitions::TRANSITION_CREATE_AND_SHIP:
                    from: !php/const Sylius\Component\Shipping\Model\ShipmentInterface::STATE_CART
                    to: !php/const Sylius\Component\Shipping\Model\ShipmentInterface::STATE_SHIPPED
