sylius_twig_hooks:
    hooks:
        'sylius_admin.order.show.content.sections.payments.item.actions':
            complete_payment_link:
                template: '@SyliusMolliePlugin/admin/order/show/content/sections/payments/item/actions/complete_payment_link.html.twig'
                priority: -100
            mollie_refund:
                template: '@SyliusMolliePlugin/admin/order/show/content/sections/payments/item/actions/refund.html.twig'
                priority: -200
