sylius_mailer:
    emails:
        payment_link:
            subject: sylius_mollie_plugin.ui.emails.payment_link
            template: "@SyliusMolliePlugin/Admin/Email/paymentLinkConfirmation.html.twig"
