imports:
    - { resource: "./resources/mollie_methods.yaml" }
    - { resource: "./resources/payment_surcharge_fee.yaml" }
    - { resource: "./resources/mollie_amount_limits.yaml" }
    - { resource: "./resources/mollie_method_image.yaml" }
    - { resource: "./resources/mollie_logger.yaml" }
    - { resource: "./resources/mollie_customer.yaml" }
    - { resource: "./resources/mollie_email_template.yaml" }
    - { resource: "./resources/order.yaml" }
    - { resource: "./resources/product_type.yaml" }
    - { resource: "./resources/payment_method.yaml" }
    - { resource: "./resources/onboarding_wizard_status.yaml" }
    - { resource: "./resources/mollie_subscription.yaml" }
    - { resource: "./resources/mollie_subscription_schedule.yaml" }
