winzou_state_machine:
    sylius_payment:
        callbacks:
            after:
                sylius_process_subscription_fail:
                    on: [ "fail" ]
                    do: [ "@sylius_mollie_plugin.payment_processing.subscription_payment_processor", "processFailed" ]
                    args: [ "object" ]

                sylius_process_subscription_success:
                    on: [ "complete" ]
                    do: [ "@sylius_mollie_plugin.payment_processing.subscription_payment_processor", "processSuccess" ]
                    args: [ "object" ]

    mollie_subscription_payment_state_graph:
        class: "%sylius_mollie_plugin.model.mollie_subscription.class%"
        property_path: paymentState
        graph: mollie_subscription_payment_state_graph
        state_machine_class: "%sylius.state_machine.class%"
        states:
            pending: ~
            ok: ~
            fail: ~
        transitions:
            begin:
                from: [ ok, fail ]
                to: pending
            success:
                from: [ pending ]
                to: ok
            failure:
                from: [ pending ]
                to: fail
        callbacks:
            before:
                mollie_subscription_payment_state_after_success:
                    on: [ "success" ]
                    do: [ "@sylius_mollie_plugin.processor.subscription_schedule_processor", "process" ]
                    args: [ "object" ]
