sylius_admin_order_payment_refund:
    path: /orders/{orderId}/payments/{id}/refund
    methods: [PUT,POST]
    defaults:
        _controller: sylius_mollie.controller.admin.refund

sylius_mollie_plugin_payum_refund:
    resource: "@PayumBundle/Resources/config/routing/refund.xml"
    prefix: /admin

sylius_refund_refund_units:
    path: /orders/{orderNumber}/refund-units
    defaults:
        _controller: sylius_mollie_plugin.sylius_mollie_plugin.controller.action.admin.refund_units_action
