name: Build and Publish Demo Image

on:
    push:
        tags:
            - '*'

    workflow_dispatch: ~

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract version info
              id: version
              run: |
                  if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
                    git fetch --tags
                    TAG_NAME=$(git describe --tags "$(git rev-list --tags --max-count=1)")
                  else
                    TAG_NAME="${GITHUB_REF#refs/tags/}"
                  fi
                  
                  MAJOR_MINOR=$(echo "$TAG_NAME" | cut -d. -f1,2)
                  
                  echo "Using tag: $TAG_NAME"
                  echo "TAG=$TAG_NAME" >> $GITHUB_ENV
                  echo "MAJOR_MINOR=$MAJOR_MINOR" >> $GITHUB_ENV

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository }}:${{ env.TAG }}
                      ghcr.io/${{ github.repository }}:${{ env.MAJOR_MINOR }}
